version: "3"
services:
    web:
        build: .
        ports:
        - "8080:80"
        links:
        - "mysql:database"
    # db mysql
    mysql:
        image: mysql:5.7.22
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: "teste"
            MYSQL_ROOT_PASSWORD: "casa"
            MYSQL_PASSWORD: "casa"
            MYSQL_USER: "casa"
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3030:3306"
        
